// {{appName}} - NEIRA Application
// Generated by @neira/cli-mcp

import { ApiResponse, User } from 'neira-shared-types';

console.log('🚀 Welcome to {{appName}}!');
console.log('This is a basic NEIRA application template.');

/**
 * Пример использования типов из neira-shared-types
 */
function createUser(name: string, email: string): User {
  return {
    id: Math.random().toString(36).substr(2, 9),
    name,
    email,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

/**
 * Пример API ответа с использованием общих типов
 */
function createApiResponse<T>(data: T, success: boolean = true): ApiResponse<T> {
  return {
    success,
    data,
    message: success ? 'Operation completed successfully' : 'Operation failed'
  };
}

/**
 * Основная логика приложения
 */
function main(): void {
  console.log('Application started successfully!');
  
  // Пример создания пользователя с типизацией
  const user = createUser('John Doe', 'john@example.com');
  console.log('Created user:', user);
  
  // Пример API ответа
  const response = createApiResponse(user);
  console.log('API Response:', response);
  
  // TODO: Добавьте здесь логику вашего приложения
}

// Запуск приложения
if (require.main === module) {
  main();
}

export { main, createUser, createApiResponse }; 