// {{appName}} - NEIRA Application
// Generated by @neira/cli-mcp

console.log('🚀 Welcome to {{appName}}!');
console.log('This is a basic NEIRA application template.');

// Основная логика приложения
function main() {
  console.log('Application started successfully!');
  
  // TODO: Добавьте здесь логику вашего приложения
}

// Запуск приложения
if (require.main === module) {
  main();
}

module.exports = { main }; 